// <auto-generated />
using Bulky.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bulky.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240303114529_AddImageColumn")]
    partial class AddImageColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bulky.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 11,
                            DisplayOrder = 17,
                            Name = "Web Development"
                        },
                        new
                        {
                            Id = 22,
                            DisplayOrder = 23,
                            Name = "Mobile App Development"
                        },
                        new
                        {
                            Id = 33,
                            DisplayOrder = 37,
                            Name = "Game Development"
                        },
                        new
                        {
                            Id = 44,
                            DisplayOrder = 42,
                            Name = "Machine Learning"
                        });
                });

            modelBuilder.Entity("Bulky.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Price100")
                        .HasColumnType("float");

                    b.Property<double>("Price50")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Cutline",
                            CategoryId = 11,
                            Description = "Web Development",
                            ISBN = "123456",
                            ImageUrl = "",
                            ListPrice = 100.0,
                            Price = 50.0,
                            Price100 = 30.0,
                            Price50 = 40.0,
                            Title = "Web Development"
                        },
                        new
                        {
                            Id = 2,
                            Author = "James",
                            CategoryId = 22,
                            Description = "Mobile App Development",
                            ISBN = "456123",
                            ImageUrl = "",
                            ListPrice = 1000.0,
                            Price = 500.0,
                            Price100 = 300.0,
                            Price50 = 400.0,
                            Title = "Mobile App Development"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Gamer",
                            CategoryId = 33,
                            Description = "Game Development",
                            ISBN = "789012",
                            ImageUrl = "",
                            ListPrice = 500.0,
                            Price = 250.0,
                            Price100 = 150.0,
                            Price50 = 200.0,
                            Title = "Game Development"
                        },
                        new
                        {
                            Id = 4,
                            Author = "AI Expert",
                            CategoryId = 44,
                            Description = "Machine Learning",
                            ISBN = "345678",
                            ImageUrl = "",
                            ListPrice = 200.0,
                            Price = 100.0,
                            Price100 = 60.0,
                            Price50 = 80.0,
                            Title = "Machine Learning"
                        });
                });

            modelBuilder.Entity("Bulky.Models.Product", b =>
                {
                    b.HasOne("Bulky.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
